### ISSUE TITLE
UX: job properties, move classpath, description, priority 

### ISSUE THREAD

**Issue by activeeon-bot** [ow2-proactive/studio#10]
<a href="https://jira.activeeon.com/browse/PWS-10" title="PWS-10">Original issue</a> created by <a href="mailto:oleg.smirnov_AT_activeeon.com">Oleg Smirnov</a> on 10, Apr 2014 at 09:50 AM - PWS-10

<hr />

Default expanded accordion should be for mandatory properties.

**Comment by fviale** [comment]
fixed by categories addition
