### ISSUE TITLE
DESIGN: Generic/properties layout could be improved

### ISSUE THREAD

**Issue by activeeon-bot** [ow2-proactive/studio#11]
<a href="https://jira.activeeon.com/browse/PWS-11" title="PWS-11">Original issue</a> created by <a href="mailto:oleg.smirnov_AT_activeeon.com">Oleg Smirnov</a> on 10, Apr 2014 at 09:50 AM - PWS-11

<hr />

two columns, auto add line when one is filled

**Comment by fviale** [comment]
not understandable
