### ISSUE TITLE
UX: Engine change to Language and put it on top (or use a good default)

### ISSUE THREAD

**Issue by activeeon-bot** [ow2-proactive/studio#14]
<a href="https://jira.activeeon.com/browse/PWS-14" title="PWS-14">Original issue</a> created by <a href="mailto:oleg.smirnov_AT_activeeon.com">Oleg Smirnov</a> on 10, Apr 2014 at 09:52 AM - PWS-14

<hr />

_No description_

**Comment by fviale** [comment]
no description
