### ISSUE TITLE
Fix style of Script arguments

### ISSUE THREAD

**Issue by activeeon-bot** [ow2-proactive/studio#16]
<a href="https://jira.activeeon.com/browse/PWS-16" title="PWS-16">Original issue</a> created by <a href="mailto:oleg.smirnov_AT_activeeon.com">Oleg Smirnov</a> on 10, Apr 2014 at 09:53 AM - PWS-16

<hr />

Add few args to see the problem

**Comment by fviale** [comment]
outdated
