### ISSUE TITLE
Dependency between workflow and task queue control?

### ISSUE THREAD

**Issue by winghc** [ow2-proactive/studio#192]
1. Do this product support dependency on taskFlow level?  Here is the my scenaria, taskFlow A is going to download 100 tables to csv files from db2 where including 100 tasks inside,  taskFlow B will import  those 100 files exported by taskFlow A to another database through 100 tasks defined.  Here taskFlow B depend on taskFlow A's success.

2.  Still for above scenaria, in taskFlow A,  I don't want to agent to run 100 connections with db2 and download data at the same time, I prefer using limited connection (resource) to do such download work, such as 5 connections for one loop,  and let other download jobs in pending status.

Appreciate your reply.

**Comment by lpellegr** [comment]
https://github.com/ow2-proactive/scheduling/issues/2319
