### ISSUE TITLE
Cannot change script language after switching between Task types

### ISSUE THREAD

**Issue by marcocast** [ow2-proactive/studio#195]
Steps to reproduce 

Create a Bash Task from the dropdown.
Click on the created task.
Change type to Native.
Save.
Change back to Script.
Try now to change the language to Ruby or other.
Save.
Refresh the page. 
The Task is still on Bash language.

This functionality works if you do not switch between Types (Script, Native, Java).

I personally don't think that makes sense to be able to switch between types for existing tasks. Kind of make sense to switch between scripting languages because you can adjust the existing task code to the language. 
But from script to native or java it is different.

**Comment by fviale** [comment]
issue does not apply any more
