### ISSUE TITLE
Set number of node failures at task level

### ISSUE THREAD

**Issue by tobwiens** [ow2-proactive/studio#219]
Hello,

I like to set the number of allowed failures for a task/job. 
![whattoset](https://cloud.githubusercontent.com/assets/6491363/12844968/f23b95d6-cc02-11e5-8ed4-3d7630a0e885.png)

What I tried to set in the job level is this:
![whatisetjob](https://cloud.githubusercontent.com/assets/6491363/12844981/fd205bf8-cc02-11e5-83dd-37d33673e339.png)

If I set this to 999 then the executions are set to 999 as shown in the first screenshot. 

Then I tried setting this here:
![whatisettask](https://cloud.githubusercontent.com/assets/6491363/12844996/1c50b806-cc03-11e5-8f7d-c2eebb0683e8.png)

If set inside the task it will overwrite the executions (999 in the first picture) to 888. 

My question is: How do I set the number of allowed failures in the Studio, or where is this number defined and where can it be changed?

**Comment by fviale** [comment]
This cannot be set directly in the studio (i.e. you cannot configure your task with a maximum number of node failures). This is a setting put at the scheduler server level.

I think an improvement could be to allow setting this at task-level, and have a default configuration on the scheduler.

**Comment by tobwiens** [comment]
The number of failures can be setup in config/scheduler/settings.ini with the setting:
```
# Maximum number of execution for a task in case of failure (node down)
pa.scheduler.task.numberofexecutiononfailure=2
```

The default value is 2.
