### ISSUE TITLE
CodeMirror in inlined (small) script editor

### ISSUE THREAD

**Issue by activeeon-bot** [ow2-proactive/studio#22]
<a href="https://jira.activeeon.com/browse/PWS-22" title="PWS-22">Original issue</a> created by <a href="mailto:oleg.smirnov_AT_activeeon.com">Oleg Smirnov</a> on 10, Apr 2014 at 09:55 AM - PWS-22

<hr />

_No description_

**Comment by fviale** [comment]
Seems like not the way to go.
