### ISSUE TITLE
Language type is lost if Script is cleared and the workflow is exported

### ISSUE THREAD

**Issue by marcocast** [ow2-proactive/studio#222]
The language type is lost if Script is cleared and the workflow is exported : 

![screen shot 2016-02-23 at 11 40 33](https://cloud.githubusercontent.com/assets/706746/13249064/50f1ec06-da22-11e5-9b03-54ee6ab884f1.png)

Steps to reproduce : 

1. Create a workflow with a python task
2. Click on the python task and delete everything in the Script text area on  the left
3. Export the workflow
4. Import the workflow

**Comment by sophiesongge** [comment]
@ow2-proactive/developers 
Could anyone view my pull request, thanks.
