### ISSUE TITLE
Workflow Title is not displayed

### ISSUE THREAD

**Issue by tobwiens** [ow2-proactive/studio#245]
![bug1missingworkflowname](https://cloud.githubusercontent.com/assets/6491363/14275097/938ba002-fb15-11e5-9650-7fa4d0b17eff.png)

**Comment by lpellegr** [comment]
Should be fixed by 99937e666f3b9fc654cdb6917170ee15d773813f.

**Comment by tobwiens** [comment]
Fixed by 99937e666f3b9fc654cdb6917170ee15d773813f
