### ISSUE TITLE
Workflow validation fails when using 360 Browser (popular web browser in China)

### ISSUE THREAD

**Issue by bamedro** [ow2-proactive/studio#267]
Whenever I modified a newly added task, such as adding a name or a script (I tried Java and R script), and it failed to pass "check". Check will prompt an error message as below:
 
Invalid workflow
At [task=Hello] [tag:job] : Error: tag name "forkEnvironment" is not allowed. Possible tag names are: <javaExecutable>,<nativeExecutable>,<scriptExecutable> at line 25 , column 69

www.360.com

**Comment by sophiesongge** [comment]
Do you have the same issue when using IE? 360 Browser is based on IE.

2016-06-10 16:31 GMT+02:00 Brian Amedro <notifications@github.com>:

> Whenever I modified a newly added task, such as adding a name or a script
> (I tried Java and R script), and it failed to pass "check". Check will
> prompt an error message as below:
>
> Invalid workflow
> At [task=Hello] [tag:job] : Error: tag name "forkEnvironment" is not
> allowed. Possible tag names are: ,, at line 25 , column 69
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ow2-proactive/studio/issues/267>, or mute the thread
> <https://github.com/notifications/unsubscribe/AJSnUT8Fo2JYq7DonYoozkkAu6rL0iIwks5qKXVSgaJpZM4IzAfk>
> .
>



-- 

Sophie Song
Tel. @ China: +86 134 26 22 77 71
Tel. @ France: +33 (0)6 20 57 23 06
Homepage:  http://www-sop.inria.fr/members/Ge.Song/index.html
Email: sophiesongge@gmail.com
           ge.song@inria.fr

**Comment by bamedro** [comment]
No, it works with IE.
