### ISSUE TITLE
Issues when resizing the browser window

### ISSUE THREAD

**Issue by marcocast** [ow2-proactive/studio#270]
Lost workflows menu and "Task", "Controls" , "Templates" buttons are not correctly displayed when reducing the size of the browser window

![screen shot 2016-06-22 at 14 47 48](https://cloud.githubusercontent.com/assets/706746/16267093/544f5086-3888-11e6-9cef-9c23604bb6b6.png)

**Comment by sophiesongge** [comment]
Does this issue still exist? I have tried it today, it seems to be good
