### ISSUE TITLE
User login not displayed when authenticated with cred file

### ISSUE THREAD

**Issue by lpellegr** [ow2-proactive/studio#276]
If you authenticate to the Scheduler or RM portal using a credential file and then open the Studio Web app, the user login is not displayed. Instead, it appears "undefined":

![capture d ecran de 2016-07-04 14-41-53](https://cloud.githubusercontent.com/assets/128898/16560763/a5d6bb8a-41f5-11e6-8659-f167873cca47.png)

The username is also not displayed when using credentials with Scheduler and RM portals. Although the username is missing, no strange value like "undefined" is displayed, which looks acceptable compared to the Studio. 

When authenticating using a credential file, the login is not known by the Web apps. The file is forwarded to the Scheduler that is the only one which is able to decrypt the encrypted file. Since the login resource used from the REST API by Webapps only returns the sessionid, the Webapps are not able to display the username of the current user that is logged.

At least, the String "undefined" should not appear to be consistent with other Web portals.

**Comment by lpellegr** [comment]
It looks like that since the Workflow Catalog has been integrated with the Studio, when authentication with credentials is used, then the Studio is no longer usable: the left panel is not displayed.

![capture d ecran de 2017-03-29 14-06-27](https://cloud.githubusercontent.com/assets/128898/24453645/066bb8d6-1489-11e7-9432-72eb0d442304.png)

Here is the error I get in the browser: 

![capture d ecran de 2017-03-29 13-59-36](https://cloud.githubusercontent.com/assets/128898/24453499/7050cfda-1488-11e7-8dbf-00fd074195ee.png)

**Comment by fviale** [comment]
Fixed by mentioned commits
