### ISSUE TITLE
Default script (task, pre, post, clean, selection, loop, etc.) should not be platform specific

### ISSUE THREAD

**Issue by bamedro** [ow2-proactive/studio#339]
Studio sometimes set empty scripts in a workflow, even if they are not filled up.
Default script language is currently bash, which is platform dependant, and will induce an error if deployed on Windows nodes. Worst, user will have to set manually a language such as javascript on all the scripts, even if he is not using the script.
Default language should be javascript for example.

**Comment by fviale** [comment]
fixed by commit b745078ed047fbc56f551aa1884d06ae2cf74d66
