### ISSUE TITLE
UX: Make BestProximity topology by default

### ISSUE THREAD

**Issue by activeeon-bot** [ow2-proactive/studio#36]
<a href="https://jira.activeeon.com/browse/PWS-36" title="PWS-36">Original issue</a> created by <a href="mailto:oleg.smirnov_AT_activeeon.com">Oleg Smirnov</a> on 10, Apr 2014 at 10:00 AM - PWS-36

<hr />

_No description_

**Comment by fviale** [comment]
BestProximity is now disabled at the scheduler level.
