### ISSUE TITLE
Studio is adding a space to the value of every GenericInfo, causing potential parsing issues

### ISSUE THREAD

**Issue by bamedro** [ow2-proactive/studio#384]
To reproduce:
1. Create a workflow
2. Add a Generic Info: name=foo, value=bar
3. Select File > Export

You get the following:
```
  <genericInformation>
    <info name="foo" value="bar "/>
  </genericInformation>
```

But it should be:
```
  <genericInformation>
    <info name="foo" value="bar"/>
  </genericInformation>
```

In particular, it prevent the START_AT to be properly parsed. Thus, a workflow with a START_AT cannot be submitted from the studio anymore (the START_AT will be ignored).

Only Workaround I see is not acceptable:
1. Export the file
2. Remove the space from the XML
3. Submit the XML from the Scheduler

**Comment by fviale** [comment]
commit bccd6fa should fix the problem, introduced on 28/03/2017, so several releases ago.
