### ISSUE TITLE
Show studio version

### ISSUE THREAD

**Issue by activeeon-bot** [ow2-proactive/studio#4]
<a href="https://jira.activeeon.com/browse/PWS-4" title="PWS-4">Original issue</a> created by <a href="mailto:vladimir.bodnartchouk_AT_activeeon.com">Vladimir Bodnartchouk</a> on 01, Oct 2013 at 17:40 PM - PWS-4

<hr />

Great for bug reports

**Comment by fviale** [comment]
fixed
