### ISSUE TITLE
Make the template interactions from the studio more clear

### ISSUE THREAD

**Issue by mbenguig** [ow2-proactive/studio#400]
Since the catalog, which is accessible from the studio, allows all possible actions related to templates (retrieve/publish), the user should only be able to create workflows directly from the studio (no choice between workflow and template). The save button will only save the current workflow as a workflow (not as a template). Moreover, the template list accessible from quick access button, could be customized by drag n dropping workflows from the catalog.

**Comment by chloegugli** [comment]
Templates have been removed from the left panel with this PR : https://github.com/ow2-proactive/studio/pull/454. So there is no more confusion.
