### ISSUE TITLE
Don't show the Direct Link URL in modal window when getting a workflow from the Catalog

### ISSUE THREAD

**Issue by bamedro** [ow2-proactive/studio#402]
I think we should not print the URL itself but only a something like 'Direct link' or 'Link'.
Now it looks like the view is not finished. Very weird.
Now:
![image](https://user-images.githubusercontent.com/1952557/29031773-919c79fa-7b8f-11e7-886d-0991a122fbfa.png)

Much nicer this way:
![image](https://user-images.githubusercontent.com/1952557/29031799-a36c19ec-7b8f-11e7-9a4b-14726ba55950.png)

**Comment by zeineb** [comment]
I can change the displayed URL: https://github.com/ow2-proactive/studio/blob/ca88a502f3520d9ca2a705404ad33017bdd0ac51/app/scripts/proactive/templates/catalog-get-revision-description.html#L17
