### ISSUE TITLE
Workflow variable contents are not preserved in docker-composed tasks

### ISSUE THREAD

**Issue by mbenguig** [ow2-proactive/studio#404]
In a docker-compose task

- I set a variable product_list with liste.txt as value
- I set a variable product_list_ajusted with liste_ajustee.txt as value

I create a docker-compose task calling these variables

Now $product_list => liste.txt and $product_list_ajusted => liste.txt_ajusted

**Comment by tobwiens** [comment]
@mbenguig 
Can you show the docker-compose task? 

The variables should be access through $variables_product_list -> .... Because the variables are pushed to the bash which execute docker-compose. Docker compose has it's own way to process bash variables. 

Furhtermore, ProActive docker-compose script engine replaces variables inside the docker-compose script. There is a blog post about it: http://blog.activeeon.com/2015/04/proactive-and-docker-schedule-and.html

**Comment by mbenguig** [comment]
Dude I am in holidays this week.. ++


Envoyé depuis mon smartphone Samsung Galaxy.
-------- Message d'origine --------De : tobwiens <notifications@github.com> Date : 18/08/2017  09:53  (GMT+01:00) À : ow2-proactive/studio <studio@noreply.github.com> Cc : mbenguig <michael.benguigui@activeeon.com>, Mention <mention@noreply.github.com> Objet : Re: [ow2-proactive/studio] Workflow variable contents are not preserved in docker-composed tasks (#404) 
@mbenguig

Can you show the docker-compose task?
The variables should be access through $variables_product_list -> .... Because the variables are pushed to the bash which execute docker-compose. Docker compose has it's own way to process bash variables.
Furhtermore, ProActive docker-compose script engine replaces variables inside the docker-compose script. There is a blog post about it: http://blog.activeeon.com/2015/04/proactive-and-docker-schedule-and.html

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ow2-proactive/studio","title":"ow2-proactive/studio","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ow2-proactive/studio"}},"updates":{"snippets":[{"icon":"PERSON","message":"@tobwiens in #404: @mbenguig \r\nCan you show the docker-compose task? \r\n\r\nThe variables should be access through $variables_product_list -\u003e .... Because the variables are pushed to the bash which execute docker-compose. Docker compose has it's own way to process bash variables. \r\n\r\nFurhtermore, ProActive docker-compose script engine replaces variables inside the docker-compose script. There is a blog post about it: http://blog.activeeon.com/2015/04/proactive-and-docker-schedule-and.html"}],"action":{"name":"View Issue","url":"https://github.com/ow2-proactive/studio/issues/404#issuecomment-323285998"}}}

**Comment by tobwiens** [comment]
Consider this xml file with variable substitution

```
<?xml version="1.0" encoding="UTF-8"?>
<job
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="urn:proactive:jobdescriptor:3.8"
     xsi:schemaLocation="urn:proactive:jobdescriptor:3.8 http://www.activeeon.com/public_content/schemas/proactive/jobdescriptor/3.8/schedulerjob.xsd"
    name="Untitled workflow" 
    priority="normal"
    onTaskError="continueJobExecution"
     maxNumberOfExecution="2"
>
  <variables>
    <variable name="output_variable" value="-------------VARIABLES WORK!---------------" />
  </variables>
  <description>
    <![CDATA[ A workflow which runs a docker compose script ]]>
  </description>
  <taskFlow>
    <task name="Docker-Compose-Task">
      <description>
        <![CDATA[ Simple hello world with docker-compose script engine. ]]>
      </description>
      <scriptExecutable>
        <script>
          <code language="docker-compose">
            <![CDATA[
ubuntuEcho:
  image: ubuntu
  command: /bin/bash -c 'sleep 5 && echo "$output_variable" '
]]>
          </code>
        </script>
      </scriptExecutable>
    </task>
  </taskFlow>
</job>
```

**Comment by mbenguig** [comment]
Moved to https://github.com/ow2-proactive/scriptengine-docker-compose/issues/24
