### ISSUE TITLE
In window Get a Workflow from the Catalog: the list of buckets doesn't refresh automatically

### ISSUE THREAD

**Issue by ShatalovYaroslav** [ow2-proactive/studio#412]
Workaround: refresh the studio page
or to save workflow.

**Comment by marcocast** [comment]
I tested on trydev and it seems to work correctly now. I will double check locally

**Comment by ShatalovYaroslav** [comment]
The issue actually has explanation:
the studio portal refresh automatically every specified time (5 sec). So you need to wait before get catalogs just after adding new bucket from other place.

If the window of catalog is already opened, the window doesn't refresh automatically. You need to close this window and push get catalog button. But this is acceptable.

The only last issue that if studio is opened and from first time "get catalog" will not show the updated buckets list.
You need to click second time "get catalog" and then it will be updated.
So the issue can not be closed.

The solution: we need explicitly update the buckets, when click on catalog button
or update the model explicitly, like in save button code.
