### ISSUE TITLE
Size of the Job Description field is limited and should be checked before submission

### ISSUE THREAD

**Issue by bamedro** [ow2-proactive/studio#449]
Of the description field is oversized, and we submit the workflow, a stacktrace is raised on server side, and we get a 504 Gateway time-out from the Studio (after the timeout period).

We should:

- Accept larger descriptions
- Check description size before submission and raise an appropriate error

Related to the following issue from scheduling:
https://github.com/ow2-proactive/scheduling/issues/3002

**Comment by fviale** [comment]
The correct way is to fix the server side problem. There is no need to check this in the studio.

**Comment by bamedro** [comment]
Yes I agree, i opened the issue in the wrong project

**Comment by fviale** [comment]
fixed in scheduler server:
https://github.com/ow2-proactive/scheduling/issues/3028
