### ISSUE TITLE
Text Area resizing problems

### ISSUE THREAD

**Issue by amouhoub** [ow2-proactive/studio#483]
* In the Studio, once you enlarge a “resizeable” textArea (like Description), you cannot resize it again to make it smaller, you can only make it bigger unless you click else somewhere in the studio.

* Furthermore, when you resize the whole side-bar (bottom-right corner), you cannot resize the width of resizeable text areas anymore, you can only make them taller unless you refresh the whole webpage this time.

**Comment by fviale** [comment]
fixed by https://github.com/ow2-proactive/studio/commit/38b26121d2261bfd421f9d841fe1c7ff5345a3c0
