### ISSUE TITLE
No control on authorized values for the workflow variables

### ISSUE THREAD

**Issue by zeineb** [ow2-proactive/studio#503]
There is no control on the entered values for the workflow variables if a range or set of values is specified.
<img width="909" alt="capture d ecran 2018-02-20 a 11 03 05" src="https://user-images.githubusercontent.com/368264/36418023-e8f60232-162d-11e8-8206-09519c7a3343.png">

<img width="902" alt="capture d ecran 2018-02-20 a 11 03 13" src="https://user-images.githubusercontent.com/368264/36418026-ed12a500-162d-11e8-8892-d460eaab32a8.png">

<img width="620" alt="capture d ecran 2018-02-20 a 11 03 29" src="https://user-images.githubusercontent.com/368264/36418030-f028a76c-162d-11e8-9284-db6d004a7711.png">

**Comment by fviale** [comment]
this is more a proactive-example project issue, range control should be added to the workflow variables models, see https://www.activeeon.com/public_content/documentation/latest/user/ProActiveUserGuide.html#_variable_model

**Comment by fviale** [comment]
replaced by https://github.com/ow2-proactive/proactive-examples/issues/70
