### ISSUE TITLE
Removing a Documentation generic info the link to user's guide does not restore

### ISSUE THREAD

**Issue by pedrovelho** [ow2-proactive/studio#505]
In a freshly created workflow the "General Parameters" shows a property Documentation with value "undefined" that points to users' guide section 3.2.

After creating a Generic Info -> "Documentation" with another value the link on the "General Parameters" tab changes. However after removing this Generic Info, the link goes back to undefined but does not point to the user guide anymore.

**Comment by zeineb** [comment]
@pedrovelho I will fix this issue. I will let you know once it is done.
