### ISSUE TITLE
auto-code-indentation broken on python tasks

### ISSUE THREAD

**Issue by paraita** [ow2-proactive/studio#529]
When editing a jython/cpython task in full screen the automatic code formating feature is messing up the indentation which leads to parse errors during execution.
To reproduce, just create a if/else block in python:

```python
if True:
    print("hello")
else:
    print("it's meeeee")
```

After writing the `print("hello") <carriage return>` segment, this line will lose its 4-space identation which is syntaxically wrong. This is done automatically so most of the time users will not see this happening and can be very frustrating when writing long scripts, and debugging those from the scheduler's portal.

**Comment by fviale** [comment]
new version of the editor seems to handle indentation correctly in python mode.
