### ISSUE TITLE
Save&close button sometimes does not save the last changes for a task

### ISSUE THREAD

**Issue by pedrovelho** [ow2-proactive/studio#564]

**Comment by pedrovelho** [comment]
It happen with me using Firefox, I am not sure yet how to reproduce it, sometimes it saves correctly. I am observing now and will post again news if I can reproduce the problem.

**Comment by chloegugli** [comment]
@pedrovelho We did several changes lately on the script edition. Could you check if you can close this issue please?

**Comment by pedrovelho** [comment]
You are right. I could not verify the same issue in 8.4.
