### ISSUE TITLE
the user name displayed in the logout button corresponds to the previous session

### ISSUE THREAD

**Issue by luispinedamx** [ow2-proactive/studio#596]
When logging into the Studio, the user name that is displayed in the logout button corresponds to the user of the previous session.

The first time that we log in, the value is even displayed as *undefined*.

<img width="433" alt="image" src="https://user-images.githubusercontent.com/29858297/45554353-7a09af80-b836-11e8-807d-db99a22c183f.png">

The next times we log in, the value always corresponds to the user of the previous session.

<img width="389" alt="image" src="https://user-images.githubusercontent.com/29858297/45554433-b3421f80-b836-11e8-92e9-a09850fd14c5.png">
<img width="371" alt="image" src="https://user-images.githubusercontent.com/29858297/45554443-ba692d80-b836-11e8-9032-8940fbf23308.png">

This bug is fixed by simply refreshing the page, but it is better to prevent it as it gives the impression of a login error.

**Comment by chloegugli** [comment]
https://github.com/ow2-proactive/studio/pull/601
