### ISSUE TITLE
Error during npm install (customizr checksum type)

### ISSUE THREAD

**Issue by medou-boushab** [ow2-proactive/studio#647]
OS: Ubuntu 18.04.2 LTS
NPM version 6.8.0
NodeJS versoin v10.15.1

Following error when installing `customizr` during `npm install`:

```
npm ERR! code EINTEGRITY
npm ERR! sha1-dbCoXl3pmRi7YhkieygwAvh1RvE= integrity checksum failed when using sha1: wanted sha1-dbCoXl3pmRi7YhkieygwAvh1RvE= but got sha512-ZD0WZKgOsOVqP2+G0vjcycK0SoOHUX5b+cr0zfHS6z5uElPEf9uexKP992Z2wJ/hMlI8VXw8yce0xsIYRWRigw== sha1-f0VBnBjY/vwTeM0coAvSqjqlAbU=. (20653 bytes)
 ```

Fixed by removing the following line in package-lock.json:

https://github.com/ow2-proactive/studio/blob/a0904629aa5297762f49efa1a8f37626824885be/package-lock.json#L921

**Comment by amouhoub** [comment]
@medou-boushab @chloegugli Normally `package-lock.json` should not be included in git files. That's an automatically generated file anyway and contents change from one machine/system to another.
We should only keep `package.json`.

**Comment by jamieburchell** [comment]
@amouhoub https://stackoverflow.com/a/44210813
