### ISSUE TITLE
Package 'jquery-ui-touch-punch' not found

### ISSUE THREAD

**Issue by medou-boushab** [ow2-proactive/studio#648]
Package `jquery-ui-touch-punch` not found during `bower install`:

```
bower jquery-ui-touch-punch#*           ENOTFOUND Package jquery-ui-touch-punch not found
```

Repository owner was changed a few month ago by Fabien, don't know if something has changed again since.

Here is the related json file:

https://github.com/ow2-proactive/studio/blob/a0904629aa5297762f49efa1a8f37626824885be/app/libs/jquery-ui-touch-punch/.bower.json#L2

**Comment by amouhoub** [comment]
@medou-boushab @chloegugli @fviale 
Since `bower` is no longer supported and since we can `npm install` almost anything maybe it's time to switch all dependencies to `npm` instead of having half on them in `bower`.
Same thing applies for **automation-dashboard**

**Comment by MaelAudren** [comment]
@medou-boushab @amouhoub how should I compile the studio to have the executable with bower that is not working ?

**Comment by medou-boushab** [comment]
Copy only App and then rename it to studio. Let me know please if you still have the same issue.

**Comment by MaelAudren** [comment]
It works thanks !
