### ISSUE TITLE
Workflow name is not encoded when querying the catalog

### ISSUE THREAD

**Issue by MaelAudren** [ow2-proactive/studio#717]
The request send by the studio to the Catalog is 
`GET http://localhost:8080/catalog/buckets/basic-examples/resources/test`
when it should be 
`GET http://localhost:8080/catalog/buckets/basic-examples/resources/test%231`

Encoding the workflow name in the URL should fix the issue.

Reproducing steps:
1/ Push to the catalog a workflow named `test#1`
2/ Create a new workflow
3/ Click on Catalog -> Get a workflow from the catalog
4/ Select the bucket where you push `test#1` then select `test#1`
Issues: 
- The revision are not displayed
- The workflow description match the previous workflow
- Using the button `Append to the current workflow` return a 500 Error

**Comment by medou-boushab** [comment]
fixed!
