### ISSUE TITLE
Presentation of items in sections should be improved.

### ISSUE THREAD

**Issue by activeeon-bot** [ow2-proactive/studio#9]
<a href="https://jira.activeeon.com/browse/PWS-9" title="PWS-9">Original issue</a> created by <a href="mailto:oleg.smirnov_AT_activeeon.com">Oleg Smirnov</a> on 10, Apr 2014 at 09:49 AM - PWS-9

<hr />

by highlighting titles/categories

**Comment by fviale** [comment]
fixed by category additions
